---
- hosts: localhost

  tasks:
  - name: Create Dynamic Resource Object definition
    uri:
      url: "https://{{ cf_server }}/api/generic_object_definitions"
      method: POST
      user: admin
      password: "{{ password }}"
      validate_certs: no
      headers:
        Content-Type:  application/json
      body_format: json
      body:
        action: create
        name: "{{ name }}"
        properties:
          attributes:
            haproxy_port: "{{ haproxy_port }}"
